version: "3.9"


volumes:
  postgres_data:


services:
  postgres:
    container_name: "kupipodariday-database"
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  backend:
    container_name: "kupipodariday-backend"
    image: "nestjs-app"
    build: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000"

  frontend:
    container_name: "kupipodariday-frontend"
    image: "react-app"
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email kettykazakova@yandex.ru -d kett.kupipodariday.nomoredomainsclub.ru api.kett.kupipodariday.nomoredomainsclub.ru --agree-tos